project_name: m3o
release:
  github:
    owner: m3o
    name: m3o
  name_template: 'Release {{.Tag}}'
before:
  hooks:
    - go mod download
builds:
- binary: api-publisher
  id: api-publisher
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  main: ./tools/api-publisher
- binary: client-generator
  id: client-generator
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  main: ./tools/client-generator
- binary: protoc-gen-openapi
  id: protoc-gen-openapi
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  main: ./tools/protoc-gen-openapi
archives:
- name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: amd64
    arm: arm
    arm64: arm64
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
